name: whoisit
version: 2.0.0+10

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
  uses-material-design: true
