name: whoisit
version: 1.2.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.6.4
  path_provider: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
  uses-material-design: true
