name: whoisit

dependencies:
  flutter:
    sdk: flutter
  path: ^1.6.2
  path_provider: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1+1

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
  uses-material-design: true
